# Compilateur
CC = gcc

# Options de compilation
CFLAGS = -Wall -Wextra -Iinclude -g

# Dossiers
SRC_DIR = src
OBJ_DIR = obj
BIN_DIR = bin

# Nom de l'exécutable
TARGET = $(BIN_DIR)/programme

# Trouve automatiquement tous les .c du dossier src/
SRC = $(wildcard $(SRC_DIR)/*.c)

# Transforme les .c en .o dans obj/
OBJS = $(SRC:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)

# Règle par défaut
all: $(TARGET)

# Construction de l'exécutable
$(TARGET): $(OBJS)
	@mkdir -p $(BIN_DIR)
	$(CC) $(CFLAGS) -o $@ $^

# Compilation des .c en .o
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Nettoyage
clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)

# Nettoyage complet
fclean: clean
	rm -f $(TARGET)

# Recompilation totale
re: fclean all
